setup.sh
This may not be the best way to go about it fixing it, but a freshly-cloned instance of p5js.org produces several warnings because there is no initial download/version.php. Running git-clone.php also results in an error because there is no site/ directory by default. This script does everything needed to eliminate the warnings I have seen so far, except for the warning addressed in https://github.com/lmccart/p5js.org/pull/68
=> script to create initial version.php file

p5-tests/array.json, p5-tests/csv.csv, p5-tests/object.json, p5-tests/sentences.txt
Here's the test files—they include all of the files in that directory that appear to be data, not just the `csv.csv` file.
=> moved test files for library into directory on the website.

download/index.php, download/release.php, setup.sh
`https://github.com/antiboredom/jside` changed to `https://github.com/processing/p5.js-editor`and other `jside` references on the PHP changed to `p5jseditor`.
Commented out code was left untouched.
=> Update editor repo and references

learn/examples_src/09_Simulate/01_Forces.js, learn/examples_src/09_Simulate/02_ParticleSystem.js
I fixed the [Particle System](http://p5js.org/learn/examples/Simulate_Particle_System.php) and [Forces](http://p5js.org/learn/examples/Simulate_Forces.php) examples. They are broken because they are using get() but the method name has been changed to copy(). I found [commit 338b468](https://github.com/processing/p5.js/commit/338b468a1bb9c05104abeacf7c7f8d8dc6cd7f4e) of p5.js which gave me the answer.
=> fixed the Particle System & Forces examples

learn/examples_src/01_Form/05_Triangle_Strip.js
In the [triangle strip example](http://p5js.org/learn/examples/Form_Triangle_Strip.php) the map function is setting the numPoints variable to a double, creating triangles with the wrong angles and an incomplete ring, so I cast it to an int.
=> fixed Triangle Strip example

examples/demos_src/01_Hello_P5/02_interactivity.js
Missing closing tags puts the code in the editor into italics.
=> Missing closing tags in Interactivity 1 example

css/main.css, heading.php, js/logo.js
The SVG image and sketch have 0.5 pixel difference in position Y, I update the parser code in logo.js to fix that image jump issue.
I also add some css to the logo container, so the logo will maintain its height, feel less jumpy. 
(This may fix the logo sketch on index page. I left it disabled on index page, please feel free to test.)
=> update main css to fix the logo container height; update svg parser with offset Y

examples/examples_src/16_Dom/07_Modify_DOM.js
Before only loading sadness:
Now, moving happiness.
=> Updates Modify DOM Example to use selectAll instead of getElements

css/main.css, examples/build_examples/build.js, examples/build_examples/mobile_example_template.ejs, examples/examples/Mobile_Acceleration_Ball_Bounce.php, examples/examples/Mobile_Acceleration_Color.php, examples/examples/Mobile_Shake_Ball_Bounce.php, examples/examples/Mobile_Simple_Draw.php, examples/examples_src/35_Mobile/00_acceleration_ballBounce.js, examples/examples_src/35_Mobile/01_simpleDraw.js, examples/examples_src/35_Mobile/02_accelerationColor.js, examples/examples_src/35_Mobile/03_shake_ballBounce.js, examples/index.php, js/examples.js
On mobile browsers, loadExamples() is called only when the display example button is tapped. 
Having issue with displayWidth and displayHeight. The canvas is 1/2 of the screen width and height. I noticed that the website's header is also only 1/2 width of the screen on the example pages.
=> Fix for mobile example pages

examples/index.php
I noticed that "Functions" appears twice on the Examples page, so removing the second one.
=> Remove duplicate Functions link

index.php
=> September front page

js/render.js
this fixes #167 but only after the code is edited. So if we change the code to say ``x <width`` rather than say it with a space like ``x < width``, it won't break the code.
But still need to find where the HTML is set to begin with in the template. I think it has to do with this https://github.com/processing/p5.js-website/blob/master/reference/assets/js/reference.js#L6934
=> set textContent instead of innerHTML for reference examples

js/render.js
I'd been using ``cnv.mouseClicked()`` to toggle sound in the inline reference examples. For example, [here](p5js.org/reference/#/p5.Amplitude). At some point, [this line in render.js](https://github.com/processing/p5.js-website/compare/master...therewasaguy:render?expand=1#diff-05aaf1f7b3e768c9abe28e85f5fe955bR169) caused them to stop working. This is because p5.Elements have methods with the same name as the p5 touch / mouse events that render.js is looking for. I changed the "gross hack" in render.js to make sure that those functions aren't preceded by a ``.``
=> tweak render.js to fix mouse/touch events on p5.Elements

examples/examples_src/33_Sound/09_Note_Envelope.js
In the [sound envelope example](http://p5js.org/examples/examples/Sound__Note_Envelope.php), because `frameCount` is `1` on the very first call to `draw()`, the note-setting code isn't triggered until one second into the sketch, which means the oscillator is playing its default frequency of 440hz for one second before the first note plays, which seems unintentional/weird (but perhaps I am wrong).
Another way to solve this might be to do `osc.freq(0)` or something during `setup()` I guess.
=> Change sound note envelope to start w/ first note

examples/examples_src/33_Sound/02_soundFormats.js
This fixes https://github.com/processing/p5.js/issues/1083.
In the end it turns out that Firefox doesn't *always* support mp3. From the [MDN page on media format support](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#MP3): 
> The MP3 audio format is supported by Firefox/Firefox for Android/Firefox OS **when the operating system provides an MP3 decoder**.
I'm not sure what those OS'es actually *are*... I'm guessing perhaps Ubuntu when you explicitly decide not to install anything proprietary on it? Anyways, I ended up crafting the language based on this funky edge case.
=> Clarify sound format support for major browsers

js/render.js
This is a hacky attempt to fix #188.
I'm actually not sure if there *is* a (reasonable) regex that will work for all possible snippets, since e.g. someone could define a `function draw() {}` within a closure that doesn't get added to the local scope... I'd rather just use a library like [esprima](http://esprima.org/) to walk the AST of the snippet and specifically pick out the top-level functions we need, but esprima isn't exactly a small library and it seems the reference pages are already a bit slow to load in some places, so I don't want to add to that.
Another more long-term option might be to actually run each sketch in its own iframe, though that could get expensive on pages with lots of examples...
So, just doing an `eval('typeof ' + f)` seemed to be the most lightweight solution …
=> Ensure an eval() in render.js won't throw

js/render.js
fixes https://github.com/processing/p5.js-website/issues/186
looks like it was removed [here](https://github.com/processing/p5.js-website/commit/ff18b48612df460d63cc84fb11ac54e657c4db0f#diff-05aaf1f7b3e768c9abe28e85f5fe955bL198), maybe for good reasons that I'm not aware of? But I think that some hash change event listener is needed to remove sketches when navigating the reference - especially sketches that make noise!
=> remove p5 instances on reference page back button (hash change)

reference/data.json
Little fix to make the y coordinate of the comment in rect()'s first example reflect what is actually being drawn.
=> Update rect() example text.

reference/data.json
fixes #218
Added parentheses to the pixelDensity() function on the Pixels[] reference code example
=> Fixed typo on Pixels[] code example

functions.php
Hi!
I recently made this experiment to make contributing to and/or deploying the website and p5 reference easier:
https://github.com/toolness/p5.js-docker
However, doing this required being able to change the return value of `getRoot()` in `functions.php`. It seems to currently be configured to return either `/p5js.org/` if the hostname is "localhost" (presumably for development purposes), and `http://p5js.org/` if it is not.
However, this strategy has some limitations. For example, it's possible to be developing the website but need it to be accessible at a hostname other than localhost: what if I'm developing the site on my laptop but want to make sure it looks OK on my cell phone? Or what if I want to host a copy of the p5 website on my LAN so that people at my learning event can …
=> Allow site root to be configured via environment variable

examples/examples_src/08_Math/14_noisewave.js
Hi, I'm p5.js beginner.
I noticed typo miss in noise wave example page.
"float" is processing grammer, so I changed "float" to "var".
please, review.
=> Fix typo on Noise Wave

download/index.php
=> 'Supported browser' for p5 not editor

get-started/index.php
I figured this could help avoid mixed-content errors, but now that I'm looking at [this](http://www.paulirish.com/2010/the-protocol-relative-url/), I guess it might be a better idea to just force the URL to https?
=> Make CDN link protocol-relative

index.php
~~This fixes #242, but not in a particularly optimal way: it basically uses user-agent sniffing (uggghh) to disable all `pointer-events`-related CSS on Edge and IE, which is what's causing the bug on those browsers. The downside is that on these browsers, the user largely loses their ability to interact with the featured background sketch. But at least the links can be clicked, which is arguably more important.~~
(The above paragraph is struck-through because my original assessment of what was causing this bug was wrong, so I revised my solution.)
This fixes #242 by making all links `display: inline-block` on IE and Edge. This does result in a bit of weirdness on these browsers--basically, the line-height of the line a link is on changes by a few pixels whenever it's hovered over--but it …
=> Make front page links clickable on Edge and IE.

css/main.css
The position of vertex section in the reference page was not correct so I fixed it with just one deletion :D
=> fix minor css bug

css/main.css
The `div.cnv_div` holding the canvas in example code snippets, highlighted below in blue, extends to the full width of the page:
Because this div is above the example code snippet in the z-order, users can't easily select the text of the code snippet.
One solution would be to explicitly set the `z-index` of the `div.cnv_div`, but I think that setting `display: inline-block` is a cleaner fix because it doesn't depend on the z-index of the example code snippet; instead, it ensures that the div holding the canvas never overlaps the example code snippet at all.
=> Make example code snippets easily selectable
