learn/examples_src/16_Dom/12_Drop.js

re: https://github.com/lmccart/p5.js/issues/370
This won't work until p5.js and p5.dom.js are updated at p5js.org as well.

Adding a new drag and drop example

---

learn/examples_src/15_Instance_Mode/01_Instantiating.js

For lmccart/p5.js#473
The exact terminology here is still open for discussion as far as I am concerned. I just wanted to take some action to make sure to keep the ball rolling.

Update instance mode vars for clarity/consistency

---

contribute/index.php

Create a new section for collecting front page works. (Under the "Teach" Section.)

add create feature work section

---

reference/data.json

removed extra 'more' in the description

fixed typo in createCanvas description

---

contribute/index.php

modify sign up link

---

js/p5.dom.js
js/p5.sound.js
reference/data.json

- update p5.sound and p5.dom
- update data.json with latest p5.sound and p5.dom and p5.js data

update data.json and addon libs

---

examples/examples_src/09_Simulate/01_Forces.js

Change the limit of position.y in Mover.prototype.checkEdges of the examples Forces.

Set the limit of the circles for placing on fund

---

download/index.php

Let's folks download the windows version of the editor.

adds windows download for editor

---

examples/examples/Interaction_Follow_1.php
examples/examples/Interaction_Follow_2.php
examples/examples/Interaction_Follow_3.php
examples/examples/Interaction_Reach_1.php
examples/examples/Interaction_Reach_2.php
examples/examples/Interaction_Reach_3.php
examples/examples_src/10_Interaction/20_Follow1.js
examples/examples_src/10_Interaction/21_Follow2.js
examples/examples_src/10_Interaction/22_Follow3.js
examples/examples_src/10_Interaction/reach1.js
examples/examples_src/10_Interaction/reach2.js
examples/examples_src/10_Interaction/reach3.js
examples/index.php

Three more examples ported over in the 'Interaction' category.

add three 'Follow' examples

---

js/scroll.js

See #176 
I'm not sure how the build works so it's not tested yet.

Fix auto-scrolling after resizing window

---

gallery/index.php

update gallery link

---

examples/examples/Simulate_Spring.php
examples/examples_src/09_Simulate/09_Spring.js
examples/index.php

from: https://processing.org/examples/spring.html

ported Spring example

---

js/scroll.js

Fix #202 
Won't work on all screens out there but should cover almost all of them.

Fix sidebar elements hidden on smaller screens

---

examples/examples/Structure_Coordinates.php

For the sake of improving clarity, I removed a word in that was probably written by accident.

grammar revision

---

tutorials/trigonometry/index.php

Fix [#1184](https://github.com/processing/p5.js/issues/1184)

Fix footer include links

---

examples/examples/Form_3D_Primitives.php
examples/examples_src/01_Form/07_3D_Primitives.js
examples/index.php

This will resolve #209 
It ports https://processing.org/examples/primitives3d.html to p5.js

added port of 3D primitive example to p5.js website

---

examples/examples_src/09_Simulate/12_BrownianMotion.js

Ported the brownian motion example from the Processing website.
Original: https://processing.org/examples/brownian.html

Brownian Motion Example

---

index.php
p5_featured/emily_xie_connections/index.html
p5_featured/emily_xie_connections/p5.js
p5_featured/emily_xie_connections/sketch.js

This is the p5.js homepage feature, as discussed via email. I spun up a local php server and tested these changes across various browsers: Chrome, Safari, Firefox. Looks mostly comparable.
Let me know if there's anything else I should change, add, or do.

p5 featured - emily xie

---

examples/examples/Math_Sine_Wave.php

Ada Lovelace Girls Who Code session at Goldman Sachs fixing typo for 268.  We think maybe there should be an emoji but Dan is incompetent with a PC.

fixing typo for #268

---

examples/examples_src/20_3D/03_materials.js

Fix [#1555](https://github.com/processing/p5.js/issues/1555)

Fix example for 3D materials

---

index.php
p5_featured/emily_xie_connections/index.html
p5_featured/emily_xie_connections/sketch.js

This fix remove the scrollbars of the background canvas.
Initial state:
Window resized:
---
This fix reduce the numbers of particles, because the distance computations take effect on the cpu and resulted frame rate.

Fix and optimize background canvas

---

examples/examples_src/33_Sound/11_Live_Input.js

There was no need for input & analyzer variable. Mic variable was missing.

mic variable added

---

examples/examples/Simulate_Brownian_Motion.php
examples/examples/Structure_Create_Graphics.php
examples/examples_src/00_Structure/08_Create_Graphics.js
examples/index.php

Adds a port of [the example for createGraphics() on the
Processing site](https://processing.org/examples/creategraphics.html).

Create Graphics Example
